# SPDX-License-Identifier: GPL-2.0

obj-y += \
	clk.o \
	clk-mul-div.o \
	clk-pll.o \
	clk-gate.o \
	clk-div.o \
	clk-div2.o \
	clk-fixup-mul-div.o

obj-$(CONFIG_RESET_CONTROLLER)	+= softrst.o
obj-y += clk-wokoo.o
