# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_CRYPTO_DEV_WOKOOCHIP) += wokoo_crypto.o
# wokoo_crypto-objs := wokoo_crypto.o wokoo_cipher.o wokoo_hash.o
# wokoo_crypto-objs := wokoo_uac.o
wokoo_crypto-objs := wokoo_sm4.o wokoo_hrng.o wokoo_sm3.o wokoo_sm2.o wokoo_sha.o wokoo_aes.o wokoo_sec.o